#! /usr/bin/env python

from sys import path as pythonpath, version_info
from os.path import dirname, join, abspath
from sysconfig import get_platform

import logging

logging.basicConfig(level=logging.INFO)

__import__("code").interact(local=locals())
